kafka.bootstrap.servers=kafka-1:9092,kafka-2:9093,kafka-3:9094
kafka.topic.ticks=gielda-ticki
kafka.topic.dict=gielda-kontrakty
kafka.topic.l1=gielda-agregaty-l1
kafka.group.id=gielda-job-v1
checkpoint.dir=s3://flink-checkpoints/gielda
checkpoint.interval.ms=30000
watermark.delay.sec=30
mysql.url=jdbc:mysql://mysql:3306/lab_db
mysql.user=root
mysql.password=password
mysql.table.l2=l2_report
kafka.topic.alerts=gielda-alerty
alert.flash.count=3
alert.flash.window.min=5
